clear all
close all
clc
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\zhipe\Downloads\signal.csv
%
% Auto-generated by MATLAB on 26-Oct-2024 15:15:21

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "e01";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data_table = readtable("C:\Users\zhipe\Downloads\signal.csv", opts);
signal=table2array(data_table);

%% Clear temporary variables
clear opts
% plot(signal)


%% Output Peak thresholds
% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, 49];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "e02";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
% Output P Peak thresholds
P = readtable("C:\Users\zhipe\Downloads\P.csv", opts);
P_thresholds=table2array(P);

% Output Q Peak thresholds
Q = readtable("C:\Users\zhipe\Downloads\Q.csv", opts);
Q_thresholds=table2array(Q);

% Output S Peak thresholds
S = readtable("C:\Users\zhipe\Downloads\S.csv", opts);
S_thresholds=table2array(S);

% Output T Peak thresholds
T = readtable("C:\Users\zhipe\Downloads\T.csv", opts);
T_thresholds=table2array(T);

clear opts

% hold on 
% xline(P_thresholds,'r')
% hold on
% xline(Q_thresholds,'g')
% hold on
% xline(S_thresholds,'black')
% hold on
% xline(T_thresholds,'y')
% 
% xlim([0 2000])
% 
% hold off

%% Time simulation
sampling_frequency=1000; % Herz;
time=linspace(0,length(signal)/sampling_frequency,length(signal));
% figure
% plot (time,signal)
% hold on
% xline(time(P_thresholds),'r')
% hold on
% xline(time(Q_thresholds),'g')
% hold on
% xline(time(S_thresholds),'black')
% hold on
% xline(time(T_thresholds),'y')
% hold off
% 
% xlim([0 time(end)])

%% setup tcp communication
tcpipClient = tcpip('127.0.0.1',55001,'NetworkRole','Client');
fopen(30);
set(tcpipClient,'Timeout',30);
% setup

%% Downsample and plotting in real time
sampling_frequency=1000;
window_length=2;

% downsampling
ds_factor=20;
signal_cut=downsample(signal,ds_factor);
time_cut=downsample(time,ds_factor);
P_thresholds_cut=floor(P_thresholds./ds_factor);
Q_thresholds_cut=floor(Q_thresholds./ds_factor);
S_thresholds_cut=floor(S_thresholds./ds_factor);
T_thresholds_cut=floor(T_thresholds./ds_factor);

phase="R";

% figure
% plotting in real time
for si=1:length(signal_cut);
    if time_cut(si)>window_length && time_cut(si)<time_cut(end)-window_length
        tic
        % pause(0.0000001)
        time_diff_ini=((time_cut-(time_cut(si)-window_length)).^2);
        time_play_ini=find(time_diff_ini==min(time_diff_ini));
        plot(time_cut(time_play_ini:si),signal_cut(time_play_ini:si))
        xlim([time_cut(si)-window_length time_cut(si)])
        drawnow
        
        for pi=1:(length(P_thresholds_cut)-1)
            if si>P_thresholds_cut(pi) && si<P_thresholds_cut(pi+1)
                status=pi;

                if si>=P_thresholds_cut(status)&& si<Q_thresholds_cut(status);
                    phase="P"

                elseif si>=Q_thresholds_cut(status)&& si<S_thresholds_cut(status);
                    phase="S"

                elseif si>=S_thresholds_cut(status)&& si<T_thresholds_cut(status);
                    phase="T"
                else
                    phase="R"
                end

            end
            % phase;
            s1=phase;
            s2="0";
            formatSpec = ' %1$s %2$s %3$s %4$s %5$s';
            a = sprintf(formatSpec,s1,s2);
            
            % fclose(tcpipClient);
            fclose(tcpipClient);
            fopen(tcpipClient);
            fwrite(tcpipClient,a);
            fclose(tcpipClient);
        end
        time_pass=toc;
    end
end

% for peaks_index=1:length(P_thresholds);
%     if index > P_thresholds(index);
%     end
% end
%% Outputing downsample data
% data_ds=downsample(data,8);
% figure;
%plot(data_ds)

%csvwrite('EKG_test_125Hz.csv',data_ds)

%% Playing the signal reference
% P_peaks=[37.41 38.40 39.32 40.27 41.17 42.13 43.10 44.04 44.95 45.95 46.86 47.77 48.80 49.70 50.64 51.55 52.51 53.37 54.36 55.23 56.15 57.06 57.99];
% Q_peaks=[37.6 38.59 39.51 40.46 41.40 42.31 43.26 44.2 45.18 46.1 47.05 48.02 48.98 49.92 50.83 51.74 52.7 53.59 54.53 55.41 56.34 57.21 58.11];
% S_peaks=[37.77 38.76 39.7 40.65 41.59 42.53 43.46 44.41 45.34 46.32 47.27 48.23 49.17 50.13 51.04 51.98 52.90 53.83 54.73 55.65 56.54 57.44 58.34];
% T_peaks=[38.03 39.01 39.93 40.87 41.81 42.76 43.68 44.63 45.6 46.54 47.5 48.46 49.45 50.37 51.27 52.18 53.11 54.01 54.95 55.85 56.78 57.65 58.57];